name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天零点执行一次同步操作
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0
        
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add upstream repository
      run: git remote add upstream https://github.com/hehonghui/awesome-english-ebooks.git

    - name: Merge upstream changes
      run: git pull upstream master --rebase

    - name: Push changes to fork
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
